import re

def filterer(ai_output:str) -> str:

    import re
    reply = re.sub(r'#\w+', '', ai_output).strip() # remove hashtags
    reply = re.sub(r'\s+', ' ', reply) # remove double+ spaces

    return reply


def escape_markdown_v2(text:str) -> str:
    """
    Escapes special characters in a string for use in a Telegram bot message with MarkdownV2 formatting.
    """
    # This function is generated by GPT-4

    def replace_hyperlink(match):
        link_text = match.group(1)
        url = match.group(2)
        return f'[{escape_special_chars(link_text)}]({url})'

    def escape_special_chars(text):
        special_chars = ['[', ']', '(', ')', '>', '#', '+', '-', '=', '|', '{', '}', '.', '!']
        escaped_chars = ['\\' + c for c in special_chars]
        for i in range(len(special_chars)):
            text = text.replace(special_chars[i], escaped_chars[i])
        return text

    hyperlink_pattern = r'\[([^\]]+)\]\(([^\)]+)\)'
    text = re.sub(hyperlink_pattern, replace_hyperlink, text)
    text = escape_special_chars(text)

    return text


def add_hyperlinks(reply:str) -> str:
    """Add hyperlinks to the text, use MarkdownV2 format (BigLab)[https://biggestlab.io]"""

    return f'{reply} [BigLab](https://biggestlab.io/)'


def postprocess(reply:str) -> str:
    reply = filterer(reply)
    reply = escape_markdown_v2(reply)
    reply = add_hyperlinks(reply)
    return reply